include: package:flutter_lints/analysis_options.yaml

analyzer:
  exclude:
    - "tool/**"
    - "bin/**"
    - "test/mock_firebase.dart"
    - "lib/widgets/files/**"
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    include_file_not_found: ignore
    unnecessary_non_null_assertion: ignore
