include: package:flutter_lints/analysis_options.yaml

analyzer:
  exclude:
    - "tool/**"
    - "bin/**"
    - "test/mock_firebase.dart"
    - "lib/widgets/files/**"

linter:
  rules:
    # Adding some basic rules but keeping it loose for now
    - avoid_print: false # The user has many prints
    - prefer_const_constructors: false
    - deprecated_member_use: false
